# Site settings
name: Huskar's blog
email: feiqiyun@126.com
author: Huskar
resume_site: https://github.com/huskar001
github: https://github.com/huskar001
baseurl: ''
description: 记录点滴
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: huskar001
highlighter: Pygments

# Build settings
markdown: kramdown